// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYTjvtU_BZimdyGpWiUQVYnfcWQ930KCc',
    appId: '1:582465137246:web:cb4f68c0baaadcf600a2cf',
    messagingSenderId: '582465137246',
    projectId: 'pharmacie-f5b6d',
    authDomain: 'pharmacie-f5b6d.firebaseapp.com',
    storageBucket: 'pharmacie-f5b6d.appspot.com',
    measurementId: 'G-T85MRK2WS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm_Lw9h5UUEM6eYGwPdQoqYfyx2JNtug0',
    appId: '1:582465137246:android:6c25dd3c40860df400a2cf',
    messagingSenderId: '582465137246',
    projectId: 'pharmacie-f5b6d',
    storageBucket: 'pharmacie-f5b6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmG2fsgFnkPb2wW7_W5ikbG2GLY9XSftk',
    appId: '1:582465137246:ios:6c4446c66b02656d00a2cf',
    messagingSenderId: '582465137246',
    projectId: 'pharmacie-f5b6d',
    storageBucket: 'pharmacie-f5b6d.appspot.com',
    iosClientId: '582465137246-171nafhelc30k0kck2dk8m32d7ue9db9.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmacie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmG2fsgFnkPb2wW7_W5ikbG2GLY9XSftk',
    appId: '1:582465137246:ios:d167408fc9cbcd6300a2cf',
    messagingSenderId: '582465137246',
    projectId: 'pharmacie-f5b6d',
    storageBucket: 'pharmacie-f5b6d.appspot.com',
    iosClientId: '582465137246-ovck0ri0dm0cup6nshhalpq1m6q65q49.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmacie.RunnerTests',
  );
}
